sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: W4hS3/NcNHJD/t+3C81j3UOQzwwnMQ576kGLkQvnwdbTkdp1NjCif4UNkiyOTEMxHg68p/wQ69QCACNInylnP291oU+xb0Kl+A4FLNenJ7urkXt23fNP6QIdtBbq1Q9vIaeduRZe91IdvToIPNCGjrM6pLEuHZjvobKIyvLsV9q2ki6Z0Wec0bqzFeyfJA7vcdnMTFtf2yIgZwzOEpaQiiO91IOYGnNRrR8K0+1Rp0qTD8jPd1ygKH+pBNIC6AphYhgnatB1JXiPvP+vkOFNAXANQmIFQIxTqIML2AZeY96cfslf/keB+c29xBncHD50gmwHmmnx7H/YB4/0jny1M3L2Y1Zn+bgMZVVBFYn4nsaMZA4ZX1/5f78x68OP9LAJKdvjUjbKMAmYHE/FbqNemtZKHA+KUSBv99dc+V4qcTs4G6jmjYIu0TUid7XFov3R+LsWOfCxkKlarpe2+2XNE2ylVk/q4aO3L0AOKOEQhIEA0uU4ERR3vqDdHYXXkvI/k3tmxwaxDo0dzq9DxB5GfwhPFvziBdLsxqKArJUPLFvEcC/G4POU61/gCtl9M/gg5pdXayzTMwGjZ2osTqajH2k/vgA1HrvRVVysqWE09nFHjr3tpSHVfW8adS0QcLxD+m6F+cHYyXUhxe1BaZSpJ2ovZ2aSujhXNZ1tTNizcbU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Main-Travelled-Roads_2809
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy